site_name: Oaktis Documentation
site_url: https://Oaktis.github.io/Oaktis/
site_description: Official documentation for Oaktis - AI-powered image & video generation
site_author: Oaktis
repo_url: https://github.com/Oaktis/Oaktis
repo_name: Oaktis/Oaktis
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quickstart.md
      - Installation: getting-started/installation.md
      - Authentication: getting-started/authentication.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Oaktis/Oaktis
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/@oaktis/sdk
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/oaktis/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/oaktis/cli
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  homepage: https://oaktis.com/?utm_source=docs&utm_medium=devhub&utm_campaign=oss-sdk&utm_content=mkdocs

copyright: Copyright &copy; 2025 Oaktis. All rights reserved.
